name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.133.223.50:2096"
UUID = "93a90093-c7c2-47e3-af98-7f55f0c01381"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
